name: Container Images Builder

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - 'docker-bake.hcl'
      - 'pgvector/**'
      - 'postgis/**'

permissions: read-all

jobs:
  build:
    name: Build ${{ matrix.name }} (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        name: [pgvector, postgis]
        arch: [amd64, arm64]
        include:
          - arch: amd64
            platform: linux/amd64
            runner: ubuntu-24.04
          - arch: arm64
            platform: linux/arm64
            runner: ubuntu-24.04-arm
    steps:
      - name: Cleanup Disk
        uses: jlumbroso/free-disk-space@main
        with:
          android: true
          dotnet: true
          haskell: true
          tool-cache: true
          large-packages: false
          swap-storage: false

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/bake-action@v6
        env:
          environment: ${{ (github.ref == 'refs/heads/main') && 'production' || 'testing' }}
          registry: ghcr.io/${{ github.repository_owner }}
          extension: ${{ matrix.name }}
          platform_suffix: "-${{ matrix.arch }}"
        with:
          push: true
          set: |
            *.platform=${{ matrix.platform }}

  merge:
    name: Merge images (${{ matrix.name }})
    runs-on: ubuntu-24.04
    needs: build
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        name: [pgvector, postgis]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create and push multiarch manifests
        env:
          environment: ${{ (github.ref == 'refs/heads/main') && 'production' || 'testing' }}
          registry: ghcr.io/${{ github.repository_owner }}
          extension: ${{ matrix.name }}
        run: |
          bash -x .github/merge-images.sh
